language: python
python:
  - "2.7.11"

addons:
  postgresql: "9.4"

cache: pip

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database mueslitest;' -U postgres
  - cp muesli.yml.example muesli.yml

# command to run tests
script: MUESLI_PATH=$(pwd) py.test muesli/tests
