language: python
dist: xenial
python:
  - "3.5.2"

addons:
  postgresql: "9.4"
  apt:
      packages:
        - lp-solve
        - postgresql-server-dev-9.4

cache: pip

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database mueslitest;' -U postgres
  - psql -c 'create database muesli;' -U postgres
  - psql -d muesli < travis-muesli-origDb.sql
  - cp muesli.yml.example muesli.yml
    # ugly hack
  - sudo wget https://www.mathi.uni-heidelberg.de/~jvisintini/lp_solve -O /usr/bin/lp_solve
  - sudo wget https://www.mathi.uni-heidelberg.de/~jvisintini/libxli_DIMACS.so -O /usr/lib/lp_solve/libxli_DIMACS.so
  - sudo python -m smtpd -n -c DebuggingServer localhost:25 &

# command to run tests
script: MUESLI_PATH=$(pwd) py.test --cov=muesli muesli/tests && codecov
