version: '2.1'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=muesli
    volumes:
      - './api.sql:/docker-entrypoint-initdb.d/travis-muesli-origDb.sql'
  muesli:
    build: .
    environment:
      - JWT_SECRET_TOKEN=secret
    volumes:
      - './:/opt/muesli4'
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - postgres
